spring:
  profiles:
    active: dev
  
  application:
    name: nova-crm

# JWT Configuration
jwt:
  secret: "nova-crm-secret-key-for-jwt-token-generation-2024"
  expiration: 86400000 # 24 hours in milliseconds

# Admin User Configuration
admin:
  username: admin
  password: nova2024

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: NOVA Dance Studio CRM API
    description: Comprehensive CRM system for managing dance studio operations
    version: 1.0.0

server:
  port: 8080

logging:
  level:
    com.nova: DEBUG
    org.springframework.web: DEBUG
