spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

# Security configurations for production
jwt:
  secret: ${JWT_SECRET:your-very-secure-jwt-secret-key-for-production-minimum-256-bits}
  expiration: ${JWT_EXPIRATION:86400000}

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:nova2024}

# Swagger configuration for production
springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.nova.crm: INFO
    org.hibernate.SQL: WARN
